# Generated by Django 4.0.5 on 2022-06-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmrcss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmrcss',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cmrcss',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='cmrcss',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cmrcss',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='cmrcss',
            name='website',
        ),
        migrations.AddField(
            model_name='cmrcss',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
