# Generated by Django 4.0.5 on 2022-06-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmrcss', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('requirements', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cmrcss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(null=True)),
                ('pricing', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cmrcss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss')),
                ('marketing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.marketing')),
            ],
        ),
        migrations.CreateModel(
            name='PreSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cmrcss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss')),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('pricing', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cmrcss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss')),
                ('presales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.presales')),
            ],
        ),
    ]
