# Generated by Django 4.0.5 on 2022-06-25 12:01

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_client_client_job_remove_account_company_account_and_more'),
        ('cmrcss', '0002_remove_cmrcss_description_remove_cmrcss_detail_and_more'),
        ('accounts', '0002_company_profile_job_created_by_alter_job_company_and_more'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('refered_by_name', models.CharField(max_length=200, null=True)),
                ('refered_source', models.CharField(max_length=200, null=True)),
                ('requirements', models.TextField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkMRK])),
                ('cmrcss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss')),
                ('leads', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
        migrations.CreateModel(
            name='OperationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('deal_details', models.TextField(null=True)),
                ('deal_status', models.CharField(choices=[('PND', 'Pending'), ('APR', 'Approved'), ('RJT', 'Rejected')], max_length=200, null=True)),
                ('detail_pricing', models.TextField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkOPR])),
                ('cmrcss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss')),
            ],
        ),
        migrations.CreateModel(
            name='PreSalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('proposal_details', models.TextField(null=True)),
                ('proposal_date', models.DateField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkPSLS])),
                ('cmrcss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss')),
            ],
        ),
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('sales_details', models.TextField(null=True)),
                ('sales_pricing', models.TextField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkSLS])),
                ('cmrcss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss')),
                ('marketinglead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.marketinglead')),
            ],
        ),
        migrations.RemoveField(
            model_name='operation',
            name='cmrcss',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='presales',
        ),
        migrations.RemoveField(
            model_name='presales',
            name='cmrcss',
        ),
        migrations.RemoveField(
            model_name='presales',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='cmrcss',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='marketing',
        ),
        migrations.DeleteModel(
            name='Marketing',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.DeleteModel(
            name='PreSales',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.AddField(
            model_name='presaleslead',
            name='saleslead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.saleslead'),
        ),
        migrations.AddField(
            model_name='operationlead',
            name='presaleslead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.presaleslead'),
        ),
    ]
