# Generated by Django 4.0.5 on 2022-06-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_client_operations'),
        ('leads', '0002_leads_marketinglead_operationlead_presaleslead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='customer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
    ]
