# Generated by Django 4.0.5 on 2022-06-25 18:28

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_profile_first_name_profile_last_name_and_more'),
        ('cmrcss', '0002_remove_cmrcss_description_remove_cmrcss_detail_and_more'),
        ('leads', '0003_alter_leads_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinglead',
            name='leads',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.leads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationlead',
            name='approved_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkOPR]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationlead',
            name='presaleslead',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.presaleslead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presaleslead',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkPSLS]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presaleslead',
            name='cmrcss',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presaleslead',
            name='saleslead',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.saleslead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='approved_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkSLS]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='cmrcss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='marketinglead',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.marketinglead'),
            preserve_default=False,
        ),
    ]
