# Generated by Django 4.0.5 on 2022-06-25 18:29

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_profile_first_name_profile_last_name_and_more'),
        ('leads', '0005_alter_marketinglead_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinglead',
            name='approved_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkMRK]),
            preserve_default=False,
        ),
    ]
