# Generated by Django 4.0.5 on 2022-06-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_profile_first_name_profile_last_name_and_more'),
        ('leads', '0007_leads_is_done_marketinglead_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='approved_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
