# Generated by Django 4.0.5 on 2022-06-25 19:41

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('cmrcss', '0002_remove_cmrcss_description_remove_cmrcss_detail_and_more'),
        ('accounts', '0003_profile_email_profile_first_name_profile_last_name_and_more'),
        ('leads', '0009_alter_saleslead_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presaleslead',
            name='approved_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkPSLS]),
        ),
        migrations.AlterField(
            model_name='presaleslead',
            name='cmrcss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='cmrcss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmrcss.cmrcss'),
        ),
    ]
