# Generated by Django 4.0.5 on 2022-06-28 18:53

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_job_document_alter_job_image'),
        ('leads', '0010_alter_presaleslead_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinglead',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkMRK]),
        ),
        migrations.AlterField(
            model_name='marketinglead',
            name='leads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads'),
        ),
        migrations.AlterField(
            model_name='operationlead',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkOPR]),
        ),
        migrations.AlterField(
            model_name='operationlead',
            name='presaleslead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.presaleslead'),
        ),
        migrations.AlterField(
            model_name='presaleslead',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkPSLS]),
        ),
        migrations.AlterField(
            model_name='presaleslead',
            name='saleslead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.saleslead'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', validators=[leads.models.checkSLS]),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='marketinglead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.marketinglead'),
        ),
    ]
