# Generated by Django 4.0.5 on 2022-06-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_profile_job_created_by_alter_job_company_and_more'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('website', models.URLField(null=True)),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.client')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.job')),
            ],
        ),
        migrations.RemoveField(
            model_name='account_company',
            name='account',
        ),
        migrations.RemoveField(
            model_name='account_company',
            name='job',
        ),
        migrations.AddField(
            model_name='customer',
            name='job',
            field=models.ManyToManyField(related_name='jobcustomer', through='customer.Customer_Job', to='accounts.job'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Account_Company',
        ),
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.ManyToManyField(related_name='jobclient', through='customer.Client_Job', to='accounts.job'),
        ),
        migrations.AddField(
            model_name='client',
            name='linkedin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.linkedin'),
        ),
    ]
