# Generated by Django 4.0.5 on 2022-06-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_client_client_job_remove_account_company_account_and_more'),
        ('leads', '0002_leads_marketinglead_operationlead_presaleslead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='operations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.operationlead'),
        ),
    ]
