# Generated by Django 4.0.5 on 2022-06-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_client_operations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
