# Generated by Django 4.0.5 on 2022-06-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_job_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.FileField(default='http://localhost:8000', upload_to=''),
            preserve_default=False,
        ),
    ]
