name: server CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        env:
          SECRET_KEY: ${{ secrets.env }}

      - name: Build docker image
        run: docker build -t ${{ secrets.image }} .
      - name: Start docker image
        run: docker run -d -p 8080:8080 ${{ secrets.image }}
